---
efiBootLoader: "grub"
efiBootLoaderId: "UmbraLinux"

grubInstall: "grub-install"
#grubInstallArgs: ["--removable"]
#grubEfiParams: [" --target=x86_64-efi", "--efi-directory=/boot/efi"]

grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootmgr: "/usr/sbin/efibootmgr"

biosBootloader: "grub"
bootInstallMethod: "generic"
grubInstallBios: "grub-install"
installHybridGRUB: false
