# Options for EFI system partition
efi:
    mountPoint:         "/boot/efi"
    recommendedSize:    300MiB
    minimumSize:        32MiB
    label:              "EFI"

# Dynamically changes the table type based on UEFI or Legacy BIOS
#defaultPartitionTableType: ""
switchablePartitionTableTypes: ["gpt", "msdos"]

enableDiskChoosing: true

userSwapChoices:
    - none      # Create no swap, use no swap
    - small     # Up to 4GB
    - suspend   # At least main memory size
    # - reuse     # Re-use existing swap, but don't create any (unsupported right now)
    - file      # To swap file instead of partition
