---
dontChroot: true
timeout: 15
name: "Disabling Live ISO Autologin on Target System"
script:
  # 1. Fix LightDM on the installed disk
  - "sed -i 's/^autologin-user=liveiso/#autologin-user=/' ${ROOT}/etc/lightdm/lightdm.conf"
  - "sed -i 's/^autologin-user-timeout=3/#autologin-user-timeout=3/' ${ROOT}/etc/lightdm/lightdm.conf"
  
  # 2. Safely remove liveiso from the target disk's configuration (if copied by unpackfs)
  - "chroot ${ROOT} userdel -r liveiso 2>/dev/null || true"
  # 2.1. Remove liveiso from sudoers so on the installed system if created liveiso user can't execute sudo w/o password
  - "sed -i '/liveiso ALL=(ALL) NOPASSWD: ALL/d' ${ROOT}/etc/sudoers"
