unpack:
    -   source: "/mnt/cdrom/live/rootfs.squashfs"
        sourcefs: "squashfs"
        destination: ""
        exclude:
            - "/etc/calamares"
            - "/usr/lib/calamares"
            - "/usr/share/calamares"
            - "/home/liveiso"
            - "/root/Desktop/Install Umbra Linux.desktop"
            - "/etc/profile.d/motd.sh"
            - "etc/lightdm/lightdm.conf.d/10-autologin.conf"
            - "/etc/sudoers.d/calamares"
