# /etc/calamares/modules/bootloader.conf
---
# Co robić, jeśli wykryto UEFI:
efiBootloader: "grub"
efiBootloaderId: "UmbraLinux"
efiBootloaderArgs: ["--removable"]

# Co robić, jeśli wykryto stary BIOS (Legacy):
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfgPath: "/boot/grub/grub.cfg"

# Gdzie instalować GRUB-a na BIOS:
# "boot" oznacza instalację w MBR głównego dysku (np. /dev/sda)
# "partition" instalowałoby wewnątrz partycji (odradzane)
grubProbe: "boot"
