# /etc/calamares/modules/mount.conf
# Konfiguracja punktów montowania dla Umbra Linux (LFS)
---
mountPoints:
  - mountPoint: /
  - mountPoint: /boot/efi
    mountOptions: [ defaults, noauto ]

extraMounts:
  - device: proc
    fs: proc
    mountPoint: /proc
  - device: sysfs
    fs: sysfs
    mountPoint: /sys
  - device: devtmpfs
    fs: devtmpfs
    mountPoint: /dev
  - device: devpts
    fs: devpts
    mountPoint: /dev/pts
