# /mnt/lfs/etc/calamares/modules/partition.conf
---
# Definiuje, gdzie Calamares ma domyślnie montować partycję ESP (EFI)
efiSystemPartition:     "/boot/efi"

# Sugerowany system plików dla zwykłych partycji Linuksa
defaultFileSystemType:  "ext4"

# Odznaczenie tej opcji zapobiega problemom na niektórych maszynach wirtualnych
enableLuksAutomatedTesting: false
